CREATE TABLE [dbo].[NACCOUNT]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[VERSION] [int] NOT NULL,
[CLIENT_ID] [bigint] NOT NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[STREET_ADDRESS1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STREET_ADDRESS2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE_PROVINCE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSTAL_CODE] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNT_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LAST_RISK_COMPLIANCE_QUESTIONNAIRE] [datetime] NULL,
[PARENT_ACCOUNT_ID] [bigint] NULL,
[IS_ACTIVE_ACCOUNT] [bit] NULL CONSTRAINT [DF_NACCOUNT_IS_ACTIVE_ACCOUNT] DEFAULT ((1)),
[ACCOUNT_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RESPONSIBILITY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE_SERVICES] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ANNUAL_EXPENSES] [bigint] NULL,
[HAS_ACCESS_TO_GLBA_PROTECTED_DATA] [bit] NULL,
[IS_LITIGATION_HOLD] [bit] NULL,
[NO_CONTRACTS] [bit] NULL,
[MAIN_CATEGORY_ID] [bigint] NULL,
[DATE_CREATED] [datetime] NULL CONSTRAINT [DF__NACCOUNT__DATE_C__593122D0] DEFAULT ('01-01-1753'),
[EXISTING_ACCOUNT_ID] [bigint] NULL,
[IS_ON_SITE_VISIT_REQUIRED] [bit] NULL,
[CONTRACT_SERVICE_PROVIDED] [bit] NOT NULL CONSTRAINT [DF__NACCOUNT__CONTRA__25869641] DEFAULT ((0)),
[REGION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_FOREIGN_SERVICE_PROVIDER] [bit] NOT NULL CONSTRAINT [DF__NACCOUNT__IS_FOR__267ABA7A] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[NACCOUNT] ADD CONSTRAINT [PK__NACCOUNT__3214EC271E3A7A34] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NACCOUNT] ADD CONSTRAINT [FK_NACCOUNT_NACCOUNT] FOREIGN KEY ([PARENT_ACCOUNT_ID]) REFERENCES [dbo].[NACCOUNT] ([ID])
GO
ALTER TABLE [dbo].[NACCOUNT] ADD CONSTRAINT [FK_NACCOUNT_NACCOUNTWF] FOREIGN KEY ([EXISTING_ACCOUNT_ID]) REFERENCES [dbo].[NACCOUNT] ([ID])
GO
